version: '3'
services:
  db:
    container_name: diziperest_db
    image: postgres:10.6
    ports:
      - "3131:5432"
    environment:
      POSTGRES_DB: diziperest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  db-admin:
    container_name: diziperest_dbadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "6432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@diziperest.com
      PGADMIN_DEFAULT_PASSWORD: zblash
